// This file is auto generated by Entity Framework Core.
// Do not edit this file by hand.
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using HotelCore.Infrastructure.Persistence;

#nullable disable

namespace HotelCore.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260503120000_FixDiscriminatorLength")]
    partial class FixDiscriminatorLength
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
